name: CSharp-CICd

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  pull_request_review:
    branches:
      - master

jobs:
  format:
    runs-on: windows-latest
    name: ğŸ‘€ Check Formatting
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2

      - name: ğŸ”® Setup Dotnet 6 Preview
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: âœ’ï¸ Set up dotnet-format
        run: dotnet tool install -g --prerelease dotnet-format

      - name: ğŸ§ Check Code Format
        run: dotnet-format --check

  build:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-10.15]
        version: [Debug, Release]

    name: Build Solution On ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2

      - name: ğŸ”® Setup Dotnet 6 Preview
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: ğŸ“¦ Restore Dependensies
        run: dotnet restore

      - name: ğŸš€ Build Project
        run: dotnet build -c ${{ matrix.version }} /p:Configuration=${{ matrix.version }} --no-restore

      - name: ğŸ§ª Run unit tests
        run: dotnet test --no-build --no-restore --configuration ${{ matrix.version }} --logger "trx;LogFileName=${GITHUB_RUN_ID}.trx"
